spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:default
logging:
  config: classpath:logback-local.xml

contentful:
  baseUrl: https://cdn.contentful.com
  token: local-token
  space: local-space
  environment: local-environment
