name: main
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maven:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0.8.0
        with:
          workload_identity_provider: projects/401363556022/locations/global/workloadIdentityPools/automation/providers/github
          service_account: automation@automation-220928.iam.gserviceaccount.com
      - run: gcloud auth configure-docker europe-north1-docker.pkg.dev
      - run: |-
          mvn deploy \
          -Dimage.repository=europe-north1-docker.pkg.dev/personal-artifacts-353012/harmelodic/blog \
          -Dimage.tag=${GITHUB_SHA:-latest}
