# $schema: http://json.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maven-deploy:
    permissions:
      contents: 'read'
      id-token: 'write' # Fetch OIDC Token for GCP Auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24
      - uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        with:
          workload_identity_provider: projects/401363556022/locations/global/workloadIdentityPools/github/providers/github-oidc
          service_account: automation@automation-220928.iam.gserviceaccount.com
      - run: gcloud auth configure-docker europe-north1-docker.pkg.dev
      - run: >
          mvn deploy
          --no-transfer-progress
          --define image.repository=europe-north1-docker.pkg.dev/personal-artifacts-353012/harmelodic/blog
          --define image.tag=${GITHUB_SHA:-latest}
          --define pact.broker.url=https://pact.harmelodic.com
          --define pact.broker.username=pact-broker-user
          --define pact.broker.password=${{ secrets.PACT_BROKER_PASSWORD }}
        # pact.broker.* used for publishing Consumer PACTs
