# $schema: http://json.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@5ccae2038ad6c1da1a103b9bc21cd9e745fcbf4f

  build-java-container-image:
    uses: harmelodic/workflows/.github/workflows/build-java-container-image.yaml@5ccae2038ad6c1da1a103b9bc21cd9e745fcbf4f
    with:
      image: europe-north1-docker.pkg.dev/personal-artifacts-353012/harmelodic/blog
    secrets: inherit
